spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_application_db?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: s323211
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

mybatis:
  configuration:
    map-underscore-to-camel-case: true
